banking/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('bankuser.urls',namespace='bankuser')),
    path('',include('user_dashboard.urls',namespace='user_dashboard')),
]

bankuser/urls.py
from django.conf.urls import url
from . import views

app_name='bankuser'
urlpatterns=[
    url('login/',views.login,name='login'),
    url('signup/',views.signup,name='signup'),
   
    ]

user_dashboard/urls.py
from django.conf.urls import url
from . import views

app_name='user_dashboard'
urlpatterns=[
    url('deposit/',views.deposite,name='deposit'),
    url('withdraw/',views.withdrawal,name='withdraw'),
    url('dashboard/',views.dashboard,name='dashboard'),
    url('logout/',views.logout,name='logout'),
    
    
    ]

bankuser/models.py
from django.db import models

# Create your models here.
class banking(models.Model):
    
    Name=models.CharField(max_length=40)
    Phone_no=models.BigIntegerField()
    Email=models.EmailField(max_length=40)
    Password=models.CharField(max_length=40)
    Count=models.IntegerField()
    Date=models.DateTimeField()
   

user_dashboard/models.py
from django.db import models

# Create your models here.
class account_details(models.Model):
    Account_number=models.CharField(max_length=14)
    Email=models.EmailField(max_length=40)
    Phone_no=models.BigIntegerField()

class deposit(models.Model):
       Account_number=models.CharField(max_length=14)
       Date=models.DateTimeField()
       Amount=models.IntegerField()
       
class withdraw(models.Model):
     Account_number=models.CharField(max_length=14)
     Date=models.DateTimeField()
     Amount=models.IntegerField()
     
class total_money(models.Model):
    Account_number=models.CharField(max_length=14)
    Balance=models.IntegerField()
    
    
    
    

bankuser/views.py
from django.shortcuts import render,redirect
from .models import banking
from user_dashboard.models import deposit,withdraw,total_money,account_details
from datetime import datetime
import random
import string
from pip._vendor.requests.api import delete

# Create your views here.
def homepage(request):
    
    return render(request,'bank.html')
def signup(request):
    if request.method=='POST':
        
        models_bank=banking()
        models_deposit=deposit()
        models_total_money=total_money()
        models_account_details=account_details()
        models_withdraw=withdraw()
        
        temp=request.POST.get('email')
        a=banking.objects.filter(Email=temp)
        
        if a.exists():
            print('user already present')
        else:
            models_bank.Name=request.POST.get('username')
            models_bank.Email=request.POST.get('email')
            models_bank.Password=request.POST.get('password')
            models_bank.Phone_no=request.POST.get('phone_number')
            models_bank.Date=datetime.now()
            models_bank.Count=0
            models_account=''.join(random.choice(string.ascii_uppercase+string.digits) for _ in range(14))
            account_number=models_account
            print(account_number)
            models_bank.save()
            models_account_details.Account_number=models_account
            models_account_details.Email=request.POST.get('email')
            models_account_details.Phone_no=request.POST.get('phone_number')
            models_account_details.save()
            models_deposit.Account_number=models_account
            models_deposit.Amount=0
            models_deposit.Date=datetime.now()
            models_deposit.save()
            models_total_money.Account_number=models_account
            models_total_money.Balance=0
            models_total_money.save()
            models_withdraw.Account_number=models_account
            models_withdraw.Amount=0
            models_withdraw.Date=datetime.now()
            models_withdraw.save()
            
    return render(request,'bank.html')




def login(request):
    
    if request.method=='POST':
        username=request.POST.get('email')
        pwd=request.POST.get('password')
        username_exist=banking.objects.filter(Email=username)
        
        
        if not username_exist.exists():
            print('enter valid email_id')
            return render(request,'bank.html',{'var1':'email doesnot exists'})
        
        
        if username_exist.exists():
            pwd_exist=banking.objects.filter(Email=username).filter(Password=pwd)
            ac=account_details.objects.filter(Email=username).values_list('Account_number',flat=True)
            account_no=list(ac).pop(0)
            print(account_no)
            request.session['account_number'] = account_no
            count=banking.objects.filter(Email=username).values_list('Count',flat=True)
            
            inc = list(count).pop(0)
            print(inc)
            
            
            if pwd_exist.exists() and inc<3:
                print('login successful')
                return redirect('/dashboard')
            
            
            if inc>=3:
                print('count exceeds')
                return render (request,'bank.html', {'error': 'Account Locked'})
            
            
            if not pwd_exist.exists():
                inc=inc+1
                banking.objects.filter(Email=username).update(Count=inc)
                return render(request,'bank.html',{'var2':'you have ', 'var3': (3-inc), 'var4': ' attempts left'})
            
    return render (request,'bank.html')

user_dashboard/views.py
from django.shortcuts import render
from bankuser.views import login
from .models import deposit
from .models import withdraw
from .models import total_money
from .models import account_details
from datetime import datetime








# Create your views here.
def deposite(request):
    if request.method=='POST':
         models_deposit=deposit()
         balance=request.POST.get('amount')
         account_no=request.session['account_number']
         models_deposit.Account_number=account_no
         models_deposit.Amount=balance
         models_deposit.Date=datetime.now()
         models_deposit.save()
         temp=total_money.objects.filter(Account_number=account_no).values_list('Balance',flat=True)
         bal=list(temp).pop(0)
         bal = bal+int(balance)
         total_money.objects.filter(Account_number=account_no).update(Balance=bal)
    return render(request,'dashboard.html')
def withdrawal(request):
    if request.method=='POST':
        models_withdraw=withdraw()
        balance=request.POST.get('amount')
        account_no=request.session['account_number']
        temp=total_money.objects.filter(Account_number=account_no).values_list('Balance',flat=True)
        bal=list(temp).pop(0)
        if bal> int(balance):
            models_withdraw.Account_number=account_no
            models_withdraw.Date=datetime.now()
            models_withdraw.Amount=balance
            models_withdraw.save()
            bal=bal-int(balance)
            total_money.objects.filter(Account_number=account_no).update(Balance=bal)
        else:
            return render(request,'dashboard.html', {'error':'not enough balance to withdraw'})
    return render(request,'dashboard.html')

def logout(request):
    del request.session['account_number']
    return render(request,'bank.html')

def dashboard(request):
    a = request.session['account_number']
    print(a)
    temp=total_money.objects.filter(Account_number=a).values_list('Balance',flat=True)
    bal=list(temp).pop(0)
    print(bal)
    return render(request,'dashboard.html', {'account_number': a, 'account_balance': bal})

templates/bank.html
{%load staticfiles%}
<!DOCTYPE html>
<html>
	<head>
		<meta charset="ISO-8859-1">
		<title>bank_account</title>
		<style>
			body{
				margin:0;
			}
			.navbar{
				width:100%;
				padding:20px;
				position:fixed;
				background-color:black; 
			}
			.navbar a{
				text-decoration:none;
				color:white;
				padding:20px;
				font-size:30px;
			}
			.navbar a:hover {
				background-color:black;
				color:gray;
			}
			#home, #signup, #login{
				height:800px;
			}
			input[type=text], input[type=number], input[type=email], input[type=password] {
				width: 20%;
				display:inline-block;
				background:#f1f1f1;
				padding: 20px;
			}
			button {
				background-color:black;
				color:white;
				padding:15px;
				font-size:18px;
				border:none;
				cursor:pointer;
				width:10%;
			}
			.image{
				margin-top: 60px;
				width:50%;
				height:40%;
			}
		</style>
	</head>
	<body>
		<div class="navbar">
			<a href="#home">home</a>
			<a href="#signup">signup</a>
			<a href="#login">login</a>
		</div>
		<div id="home">
		<br><br><br><br><br>
			<center>
				<h1>Mayank Sharma's Bank</h1>
				<img src="{%static 'images/download.jpg'%}" class="image">
			</center>
		</div>
		<div id="signup">
			<br><br><br><br> 
			<form action="{%url 'bankuser:signup'%}" method="POST">
				{%csrf_token%}
				<input type="text" name="username" placeholder="NAME">
				<br>
				<input type="number" name="phone_number" placeholder="ENTER PHONE NO.">
				<br>
				<input type="email" name="email" placeholder="EMAIL">
				<br>
				<input type="password" name="password" placeholder="PASSWORD">
				<br>
				<button type="submit" name="signup">Sign Up</button>
			</form>
		</div>
		<div id="login">
			<br><br><br><br>
			<form action="{%url 'bankuser:login'%}" method="POST">
				{%csrf_token%}
				<input type="email" name="email" placeholder="EMAIL">
				<br>
				<input type="password" name="password" placeholder="PASSWORD">
				<br>
				<button type="submit" name="login">Login</button>
			</form>
			{{error}}{{var1}}{{var2}}{{var3}}{{var4}}
		</div>
	</body>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
<meta charset="ISO-8859-1">
<title>bank account</title>
<style>
.navbar{
position:fixed;
width:100%;
background-color:black;
color:white;
}

.navbar a{
text-decoration:none;
font-size:35px;
color:white;
padding:20px;
}
#table,#deposit,#withdraw{
height:600px;
padding:20px;
}

table{
height:50px;
padding:8px;
color:black;
width:30%;
}
</style>
</head>
<body>
<div class="navbar">
   <a href="#table">Home  </a>
   <a href="#deposit">Deposit  </a>
   <a href="#withdraw">Withdraw  </a>
   <a href="{%url 'user_dashboard:logout'%}" >logout</a>
   
   
</div>
<div id="table">
<center>
<br><br><br><br>
<table border=5>
<tr>
    <th>Ac.Number</th>
    <th>Ac. Balance</th>
</tr>
<tr>
    <td>{{account_number}}</td>
    <td>Rs  {{account_balance}}</td>
</tr>
</table>
</center>

</div>

<div id="deposit">
<br><br><br>
<form action="{%url 'user_dashboard:deposit'%}" method="post">
{%csrf_token%}
<input type="number" name="amount" placeholder="ENTER AMOUNT TO DEPOSIT">
<button type="submit">submit</button>
</form>
</div>
<div id="withdraw">
<br><br><br>
<form action="{%url 'user_dashboard:withdraw'%}" method="post">
{%csrf_token%}
<input type="number" name="amount" placeholder="ENTER AMOUNT TO withdraw">

<button type="submit">submit</button>
{{error}}
</form>
</div>



</body>
</html>